# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadesProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termmino', models.DateField(verbose_name='Data de Término')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Custo')),
            ],
        ),
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=200, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='Matrícula')),
            ],
        ),
        migrations.CreateModel(
            name='MembrosProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.Membros', verbose_name='Membro')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_termmino', models.DateTimeField(auto_now_add=True, verbose_name='Data de Término')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('metodologia', models.TextField(verbose_name='Metodologia')),
                ('resultados_esperados', models.TextField(verbose_name='Resultados Esperados')),
            ],
        ),
        migrations.AddField(
            model_name='membrosprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.Projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='atividadesprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appprojetos.Projeto', verbose_name='Projeto'),
        ),
    ]
